//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletion) DeepCopyInto(out *VPCDeletion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletion.
func (in *VPCDeletion) DeepCopy() *VPCDeletion {
	if in == nil {
		return nil
	}
	out := new(VPCDeletion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCDeletion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletionInitParameters) DeepCopyInto(out *VPCDeletionInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletionInitParameters.
func (in *VPCDeletionInitParameters) DeepCopy() *VPCDeletionInitParameters {
	if in == nil {
		return nil
	}
	out := new(VPCDeletionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletionList) DeepCopyInto(out *VPCDeletionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCDeletion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletionList.
func (in *VPCDeletionList) DeepCopy() *VPCDeletionList {
	if in == nil {
		return nil
	}
	out := new(VPCDeletionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCDeletionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletionObservation) DeepCopyInto(out *VPCDeletionObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletionObservation.
func (in *VPCDeletionObservation) DeepCopy() *VPCDeletionObservation {
	if in == nil {
		return nil
	}
	out := new(VPCDeletionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletionParameters) DeepCopyInto(out *VPCDeletionParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletionParameters.
func (in *VPCDeletionParameters) DeepCopy() *VPCDeletionParameters {
	if in == nil {
		return nil
	}
	out := new(VPCDeletionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletionSpec) DeepCopyInto(out *VPCDeletionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
	out.InitProvider = in.InitProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletionSpec.
func (in *VPCDeletionSpec) DeepCopy() *VPCDeletionSpec {
	if in == nil {
		return nil
	}
	out := new(VPCDeletionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDeletionStatus) DeepCopyInto(out *VPCDeletionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDeletionStatus.
func (in *VPCDeletionStatus) DeepCopy() *VPCDeletionStatus {
	if in == nil {
		return nil
	}
	out := new(VPCDeletionStatus)
	in.DeepCopyInto(out)
	return out
}
